dist: trusty
sudo: false

language: shell
branches:
  only:
    - master

env:
  # This environment variable tells Terraform not to prompt for input.
  - TF_INPUT=false

# Install terraform
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
  - cd project-prod
  - terraform init
  
#run the plan
script: terraform plan

deploy:
- provider: script
  skip_cleanup: true
  script: ls -a
  on:
    branch: master
